#!/usr/bin/env python3
"""Generate SaturdayPresets.h from Saturday.rpl factory preset bank."""

import base64
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
RPL_PATH = SCRIPT_DIR.parent.parent / "Saturday.rpl"
OUT_PATH = SCRIPT_DIR.parent / "Source" / "SaturdayPresets.h"

PRESET_RE = re.compile(r"<PRESET `([^`]+)`\s*\n\s*(\S+)", re.MULTILINE)


def parse_rpl(path: Path) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    presets = []
    for name, b64 in PRESET_RE.findall(text):
        decoded = base64.b64decode(b64).decode("ascii").strip()
        values = decoded.split()
        if len(values) < 8:
            raise ValueError(f"Preset '{name}' has fewer than 8 slider values: {values}")
        mode = int(float(values[0]))
        drive = float(values[1])
        tone = float(values[2])
        mix = float(values[3])
        # values[4] output (hidden), values[5] auto gain (hidden) — ignored
        quality = int(float(values[6]))
        gate = float(values[7])
        presets.append(
            {
                "name": name,
                "mode": mode,
                "drive": drive,
                "tone": tone,
                "mix": mix,
                "quality": quality,
                "gate": gate,
            }
        )
    return presets


def format_float(v: float) -> str:
    if v == int(v):
        return f"{int(v)}.f"
    return f"{v:.1f}f"


def generate_header(presets: list[dict]) -> str:
    lines = [
        "#pragma once",
        "",
        "// Auto-generated by scripts/generate-presets.py — do not edit by hand.",
        "",
        "struct SaturdayPreset",
        "{",
        "    const char* name;",
        "    int mode;     // 0=Cassette, 1=Tube, 2=Iconic",
        "    float drive;  // 0–100",
        "    float tone;   // -100–100",
        "    float mix;    // 0–100",
        "    int quality;  // 0=Standard, 1=Hi-Fi, 2=Ultra",
        "    float gate;   // -80–0",
        "};",
        "",
        f"constexpr int kNumFactoryPresets = {len(presets)};",
        "",
        "constexpr SaturdayPreset kFactoryPresets[] =",
        "{",
    ]
    for p in presets:
        name = p["name"].replace("\\", "\\\\").replace('"', '\\"')
        lines.append(
            f'    {{ "{name}", {p["mode"]}, {format_float(p["drive"])}, '
            f'{format_float(p["tone"])}, {format_float(p["mix"])}, '
            f'{p["quality"]}, {format_float(p["gate"])} }},'
        )
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    if not RPL_PATH.is_file():
        print(f"Error: {RPL_PATH} not found", file=sys.stderr)
        return 1
    presets = parse_rpl(RPL_PATH)
    if not presets:
        print("Error: no presets found", file=sys.stderr)
        return 1
    OUT_PATH.write_text(generate_header(presets), encoding="utf-8")
    print(f"Wrote {len(presets)} presets to {OUT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
