#pragma once

// Auto-generated by scripts/generate-presets.py — do not edit by hand.

struct SaturdayPreset
{
    const char* name;
    int mode;     // 0=Cassette, 1=Tube, 2=Iconic
    float drive;  // 0–100
    float tone;   // -100–100
    float mix;    // 0–100
    int quality;  // 0=Standard, 1=Hi-Fi, 2=Ultra
    float gate;   // -80–0
};

constexpr int kNumFactoryPresets = 29;

constexpr SaturdayPreset kFactoryPresets[] =
{
    { "Warm Tape", 0, 35.f, -15.f, 100.f, 1, -28.f },
    { "Vocal Glow", 2, 18.f, 8.f, 40.f, 1, -80.f },
    { "Drum Punch", 1, 48.f, 5.f, 100.f, 1, -28.f },
    { "Mix Glue", 0, 18.f, -8.f, 100.f, 1, -28.f },
    { "Tube Weight", 1, 38.f, -22.f, 100.f, 1, -28.f },
    { "Subtle Warmth", 0, 12.f, -5.f, 100.f, 1, -28.f },
    { "Heavy Tape", 0, 72.f, -25.f, 100.f, 1, -28.f },
    { "Bright Tube", 1, 55.f, 30.f, 100.f, 2, -28.f },
    { "Bass Thickener", 1, 38.f, -35.f, 100.f, 1, -28.f },
    { "Master Saturday", 0, 15.f, -10.f, 100.f, 2, -28.f },
    { "Acoustic Air", 1, 20.f, 18.f, 60.f, 1, -28.f },
    { "Lo-Fi Crush", 0, 85.f, -40.f, 100.f, 1, -80.f },
    { "Parallel Sat", 1, 65.f, 0.f, 45.f, 2, -28.f },
    { "Bus Character", 1, 28.f, -14.f, 100.f, 2, -28.f },
    { "Synth Heat", 1, 42.f, 8.f, 80.f, 1, -28.f },
    { "Neon Presence", 2, 48.f, 16.f, 72.f, 2, -80.f },
    { "Quiet Line", 0, 26.f, -10.f, 100.f, 1, -44.f },
    { "Ribbon Vocal", 1, 30.f, -16.f, 82.f, 1, -28.f },
    { "Snare Crack", 1, 44.f, 14.f, 100.f, 2, -28.f },
    { "Room Glue", 1, 24.f, -18.f, 68.f, 1, -28.f },
    { "Direct Heat", 1, 28.f, -28.f, 100.f, 1, -28.f },
    { "12AX7 Push", 1, 52.f, 8.f, 100.f, 2, -28.f },
    { "2 Inch Machine", 0, 44.f, -18.f, 100.f, 2, -28.f },
    { "Cassette Night", 0, 58.f, -28.f, 100.f, 1, -80.f },
    { "Bloom Stack", 2, 38.f, 6.f, 52.f, 2, -28.f },
    { "Sunlit Strings", 2, 32.f, 12.f, 55.f, 1, -28.f },
    { "Icon Driver", 2, 62.f, 8.f, 88.f, 2, -36.f },
    { "Console Smoke", 1, 46.f, -6.f, 38.f, 2, -28.f },
    { "Tape Print", 0, 20.f, -14.f, 100.f, 2, -28.f },
};
